name: Maven CI
on:
  push:
    branches:
      - main
      - 'releases/[1-9]+.[0-9]+.x'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'attribute.txt'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'INDIVIDUAL_CONTRIBUTOR_LICENSE.md'
      - 'LICENSE'
      - 'NOTICE.txt'
      - 'OSSMETADATA'
      - 'install-*.sh'
      - '**/README.md'
  pull_request:
    branches:
      - main
      - 'releases/[1-9]+.[0-9]+.x'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'attribute.txt'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'INDIVIDUAL_CONTRIBUTOR_LICENSE.md'
      - 'LICENSE'
      - 'NOTICE.txt'
      - 'OSSMETADATA'
      - 'install-*.sh'
      - '**/README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Set Maven Project Version
        shell: bash
        run: |
          BUILD_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout | tail -1 | tr -d '\r\n')
          [[ "$BUILD_VERSION" != *"-SNAPSHOT" ]] && BUILD_VERSION="${BUILD_VERSION}-SNAPSHOT" && ./mvnw --batch-mode versions:set -DnewVersion=$BUILD_VERSION || true
      - name: Build Maven Project
        if: success()
        run: ./mvnw --batch-mode install -D ci.build
