name: Sourcehawk Scan
on:
  push:
    branches:
      - main
      - 'releases/[1-9]+.[0-9]+.x'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sourcehawk Scan
        uses: optum/sourcehawk-scan-github-action@main



